version: '3.9'

services:
  mongodb:
    image: mongo:latest
    restart: always
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
      - db:/data/configdb
    networks:
      - backend
  chat-app-api:
    depends_on:
      - mongodb
    restart: always
    build: ./server
    env_file: ./.env
    environment:
      - CLIENT_UI_URL=$CLIENT_UI_URL
      - DATABASE_HOST=mongodb
      - DATABASE_NAME=$MONGODB_DATABASE_NAME
      - DATABASE_PORT=$MONGODB_DOCKER_PORT
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - be:/usr/local/chat-app-api/images
   
    networks:
      - backend
      - frontend
  chat-appp-ui:
    depends_on:
      - chat-app-api
    build:
      context: ./client
      args:
        - REACT_APP_SERVER_API_URL=$SERVER_API_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - frontend

volumes:
  db:
  be:

networks:
  frontend:
  backend: